# ==============================================================================
# Fin-FFB Large (Fat) Configuration
# ------------------------------------------------------------------------------
# Optimized for: High-end Consumer GPUs (16GB-24GB VRAM, e.g., RTX 3090/4090).
# ==============================================================================

model:
  # Model Dimensions
  vocab_size: 30000
  d_model: 1024            # Maximized width for high representational capacity.
  num_layers: 3            # Keeps the model Fast (low latency) despite width.
  num_heads: 16            # d_head = 64.
  dropout: 0.1
  ffn_factor: 4            # d_ffn = 4096.
  
  # Initialization & Normalization
  initializer_range: 0.02

training:
  # Hardware & Efficiency
  batch_size: 4           # Adjusted for memory (4).
  gradient_accumulation_steps: 32 # Effective batch size = 128 (same rate as original BERT (as for total token per batch)).
  mixed_precision: "bf16"
  
  # Optimization
  learning_rate: 5.0e-4    # Higer LR
  weight_decay: 0.01
  betas: [0.9, 0.98]
  eps: 1.0e-6
  clip_grad_norm: 1.0
  
  # Scheduler
  warmup_steps_perc: 0.1   # Linear increase of LR at the start (10% of total steps).

dataset:
  # MLM Configuration
  max_seq_len: 1024
  mask_probability: 0.4 # 0.15 as default, using higher rate (I will only train the model with MLM due to time and hardware constraints)
